services:
  web:
    image: nichfournier/launchpad-web:latest
    container_name: orange-web
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - postgres

  nginx:
    image: nichfournier/launchpad-nginx:latest
    container_name: orange-nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

  tunnel:
    image: nichfournier/launchpad-tunnel:latest
    container_name: orange-tunnel
    command: tunnel --no-autoupdate --config /app/config.yml run
    environment:
      - TUNNEL_ID=${TUNNEL_ID}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=America/Los_Angeles
    depends_on:
      - web
    restart: unless-stopped
    hostname: launchpad.nicholasfournier.com

  postgres:
    image: postgres:16-alpine
    container_name: orange-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: orange-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - 8080:80

volumes:
  static_volume:
  media_volume:
  db:
