name: orange-server

services:
  web:
    image: nichfournier/launchpad-web:latest
    container_name: web
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - postgres
    networks:
      - orange-network

  nginx:
    image: nginx:1.27.3-perl
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - orange-network

  tunnel:
    image: cloudflare/cloudflared:2024.12.2
    container_name: tunnel
    command: tunnel --no-autoupdate --config /app/config.yml run
    volumes:
      - ./tunnel.yml:/app/config.yml
    environment:
      - TUNNEL_ID=${TUNNEL_ID}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=America/Los_Angeles
    depends_on:
      - web
    restart: unless-stopped
    hostname: launchpad.nicholasfournier.com
    networks:
      - orange-network
      - osrm-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - orange-network

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - 8080:80
    networks:
      - orange-network

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    ports:
      # - "61208-61209:61208-61209"
      - "61208:61208"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-w  # Enable the web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    pid: host
    networks:
      - orange-network

volumes:
  static_volume:
  media_volume:
  db:

networks:
  orange-network:
    driver: bridge
    name: orange-network
  osrm-network:
    external: true
