apiVersion: v1
kind: Namespace
metadata:
  name: launchpad
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
  namespace: launchpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-volume
  namespace: launchpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: launchpad
data:
  DJANGO_ENV: production
  PG_DBNAME: launchpad
  PG_HOST: your-db-host
  TZ: America/Los_Angeles
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: launchpad
data:
  nginx.conf: |
    worker_processes 4;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;

        upstream launchpad {
            server web:9000;
        }

        server {
            listen 80;
            server_name orange;

            location / {
                proxy_pass http://launchpad;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_redirect off;
            }

            location /static/ {
                alias /app/staticfiles/;
            }

            location /media/ {
                alias /app/mediafiles/;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-config
  namespace: launchpad
data:
  config.yml: |
    ingress:
      - hostname: "launchpad.nicholasfournier.com"
        service: http://nginx:80
      - hostname: "router.nicholasfournier.com"
        service: http://osrm-nginx:5000
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: launchpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nichfournier/launchpad-web:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: launchpad-secrets
          volumeMounts:
            - name: static-volume
              mountPath: /app/staticfiles
            - name: media-volume
              mountPath: /app/mediafiles
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: launchpad
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: launchpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.3-perl
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: static-volume
              mountPath: /app/staticfiles
            - name: media-volume
              mountPath: /app/mediafiles
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: launchpad
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  namespace: launchpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel
  template:
    metadata:
      labels:
        app: tunnel
    spec:
      containers:
        - name: tunnel
          image: cloudflare/cloudflared:2024.12.2
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /app/config.yml
            - run
          envFrom:
            - secretRef:
                name: launchpad-secrets
          volumeMounts:
            - name: tunnel-config
              mountPath: /app/config.yml
              subPath: config.yml
      volumes:
        - name: tunnel-config
          configMap:
            name: tunnel-config
