name: thinkbox-db

services:
  postgres:
    image: nichfournier/launchpad-postgres:latest  # Default: Pull from remote
    container_name: thinkbox-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ${BACKUP_PATH}:/backups
      - .env:/etc/environment:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: thinkbox-pgadmin
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:80

volumes:
  pg_data:
